In [534]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier

In [422]:
customers = pd.read_excel("C://python_projects//machine_learning//Capstone_Finding_Marketing_Insights//CustomersData.xlsx")
tax_amount = pd.read_excel("C://python_projects//machine_learning//Capstone_Finding_Marketing_Insights//Tax_amount.xlsx")
discount = pd.read_csv("C://python_projects//machine_learning//Capstone_Finding_Marketing_Insights//Discount_Coupon.csv")
marketing = pd.read_csv("C://python_projects//machine_learning//Capstone_Finding_Marketing_Insights//Marketing_Spend.csv")
onlinesales = pd.read_csv("C://python_projects//machine_learning//Capstone_Finding_Marketing_Insights//Online_Sales.csv")

In [423]:
customers.shape

(1468, 4)

In [424]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1468 entries, 0 to 1467
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   CustomerID     1468 non-null   int64 
 1   Gender         1468 non-null   object
 2   Location       1468 non-null   object
 3   Tenure_Months  1468 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 46.0+ KB


In [425]:
customers.isna().sum()

CustomerID       0
Gender           0
Location         0
Tenure_Months    0
dtype: int64

In [426]:
customers.duplicated().sum()

np.int64(0)

In [427]:
customers.describe().T

count          mean          std      min      25%      50%  \
CustomerID     1468.0  15314.386240  1744.000367  12346.0  13830.5  15300.0   
Tenure_Months  1468.0     25.912125    13.959667      2.0     14.0     26.0   

                    75%      max  
CustomerID     16882.25  18283.0  
Tenure_Months     38.00     50.0

In [428]:
customers.describe(include=object).T

count unique         top freq
Gender    1468      2           F  934
Location  1468      5  California  464

In [429]:
tax_amount.shape

(20, 2)

In [430]:
tax_amount.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Product_Category  20 non-null     object 
 1   GST               20 non-null     float64
dtypes: float64(1), object(1)
memory usage: 452.0+ bytes


In [431]:
tax_amount.isna().sum()

Product_Category    0
GST                 0
dtype: int64

In [432]:
tax_amount.duplicated().sum()

np.int64(0)

In [433]:
tax_amount.describe().T

count    mean       std   min     25%  50%   75%   max
GST   20.0  0.1165  0.052443  0.05  0.0875  0.1  0.18  0.18

In [434]:
tax_amount.describe(include=object).T

count unique       top freq
Product_Category    20     20  Nest-USA    1

In [435]:
discount.shape

(204, 4)

In [436]:
discount.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Month              204 non-null    object
 1   Product_Category   204 non-null    object
 2   Coupon_Code        204 non-null    object
 3   Discount_pct       204 non-null    int64 
dtypes: int64(1), object(3)
memory usage: 6.5+ KB


In [437]:
discount.isna().sum()

Month                0
Product_Category     0
Coupon_Code          0
Discount_pct         0
dtype: int64

In [438]:
discount.duplicated().sum()

np.int64(0)

In [439]:
discount.describe().T

count  mean       std   min   25%   50%   75%   max
Discount_pct  204.0  20.0  8.185052  10.0  10.0  20.0  30.0  30.0

In [440]:
discount.describe(include=object).T

count unique      top freq
Month               204     12      Jan   17
Product_Category    204     17  Apparel   12
Coupon_Code         204     48  EXTRA20    8

In [441]:
marketing.shape

(365, 3)

In [442]:
marketing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           365 non-null    object 
 1   Offline_Spend  365 non-null    int64  
 2   Online_Spend   365 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 8.7+ KB


In [443]:
marketing.isna().sum()

Date             0
Offline_Spend    0
Online_Spend     0
dtype: int64

In [444]:
marketing.duplicated().sum()

np.int64(0)

In [445]:
marketing.describe().T

count         mean         std     min     25%      50%  \
Offline_Spend  365.0  2843.561644  952.292448  500.00  2500.0  3000.00   
Online_Spend   365.0  1905.880740  808.856853  320.25  1258.6  1881.94   

                   75%      max  
Offline_Spend  3500.00  5000.00  
Online_Spend   2435.12  4556.93

In [446]:
marketing.describe(include=object).T

count unique         top freq
Date   365    365  12/31/2019    1

In [447]:
onlinesales.shape

(52924, 10)

In [448]:
onlinesales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52924 entries, 0 to 52923
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   CustomerID           52924 non-null  int64  
 1   Transaction_ID       52924 non-null  int64  
 2   Transaction_Date     52924 non-null  int64  
 3   Product_SKU          52924 non-null  object 
 4   Product_Description  52924 non-null  object 
 5   Product_Category     52924 non-null  object 
 6   Quantity             52924 non-null  int64  
 7   Avg_Price            52924 non-null  float64
 8   Delivery_Charges     52924 non-null  float64
 9   Coupon_Status        52924 non-null  object 
dtypes: float64(2), int64(4), object(4)
memory usage: 4.0+ MB


In [449]:
onlinesales.isna().sum()

CustomerID             0
Transaction_ID         0
Transaction_Date       0
Product_SKU            0
Product_Description    0
Product_Category       0
Quantity               0
Avg_Price              0
Delivery_Charges       0
Coupon_Status          0
dtype: int64

In [450]:
onlinesales.duplicated().sum()

np.int64(0)

In [451]:
onlinesales.describe().T

count          mean          std          min         25%  \
CustomerID        52924.0  1.534671e+04  1766.556020     12346.00     13869.0   
Transaction_ID    52924.0  3.240983e+04  8648.668977     16679.00     25384.0   
Transaction_Date  52924.0  2.019068e+07   333.363988  20190101.00  20190412.0   
Quantity          52924.0  4.497638e+00    20.104711         1.00         1.0   
Avg_Price         52924.0  5.223765e+01    64.006882         0.39         5.7   
Delivery_Charges  52924.0  1.051763e+01    19.475613         0.00         6.0   

                          50%          75%          max  
CustomerID           15311.00     16996.25     18283.00  
Transaction_ID       32625.50     39126.25     48497.00  
Transaction_Date  20190713.00  20190927.00  20191231.00  
Quantity                 1.00         2.00       900.00  
Avg_Price               16.99       102.13       355.74  
Delivery_Charges         6.00         6.50       521.36

In [452]:
onlinesales.describe(include=object).T

count unique  \
Product_SKU          52924   1145   
Product_Description  52924    404   
Product_Category     52924     20   
Coupon_Status        52924      3   

                                                                   top   freq  
Product_SKU                                             GGOENEBJ079499   3511  
Product_Description  Nest Learning Thermostat 3rd Gen-USA - Stainle...   3511  
Product_Category                                               Apparel  18126  
Coupon_Status                                                  Clicked  26926

In [453]:
onlinesales.head()

CustomerID  Transaction_ID  Transaction_Date     Product_SKU  \
0       17850           16679          20190101  GGOENEBJ079499   
1       17850           16680          20190101  GGOENEBJ079499   
2       17850           16681          20190101  GGOEGFKQ020399   
3       17850           16682          20190101  GGOEGAAB010516   
4       17850           16682          20190101  GGOEGBJL013999   

                                 Product_Description Product_Category  \
0  Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA   
1  Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA   
2              Google Laptop and Cell Phone Stickers           Office   
3  Google Men's 100% Cotton Short Sleeve Hero Tee...          Apparel   
4                    Google Canvas Tote Natural/Navy             Bags   

   Quantity  Avg_Price  Delivery_Charges Coupon_Status  
0         1     153.71               6.5          Used  
1         1     153.71               6.5          Used  
2         1       2.05               6.5          Used  
3         5      17.53               6.5      Not Used  
4         1      16.50               6.5          Used

In [454]:
onlinesales['Transaction_Date']= pd.to_datetime(onlinesales['Transaction_Date'],format='%Y%m%d')

In [455]:
onlinesales['Year']=onlinesales['Transaction_Date'].dt.year
onlinesales['Month']= onlinesales['Transaction_Date'].dt.month
onlinesales['Month_Name']= onlinesales['Transaction_Date'].dt.strftime('%b')

In [456]:
marketing['Date'] = pd.to_datetime(marketing['Date'])
marketing['Year'] = marketing['Date'].dt.year
marketing['Month'] = marketing['Date'].dt.month
marketing['Month_Name'] = marketing['Date'].dt.strftime('%b')

In [457]:
discount['Month'] = discount['Month'].str.strip().str.capitalize()

In [458]:
onlinesales[['Transaction_Date', 'Year', 'Month', 'Month_Name']].head()

Transaction_Date  Year  Month Month_Name
0       2019-01-01  2019      1        Jan
1       2019-01-01  2019      1        Jan
2       2019-01-01  2019      1        Jan
3       2019-01-01  2019      1        Jan
4       2019-01-01  2019      1        Jan

In [459]:
marketing[['Date', 'Year', 'Month', 'Month_Name']].head()

Date  Year  Month Month_Name
0 2019-01-01  2019      1        Jan
1 2019-01-02  2019      1        Jan
2 2019-01-03  2019      1        Jan
3 2019-01-04  2019      1        Jan
4 2019-01-05  2019      1        Jan

In [460]:
discount['Month'].unique()

array(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep',
       'Oct', 'Nov', 'Dec'], dtype=object)

In [461]:
onlinesales=onlinesales.merge(tax_amount,on='Product_Category',how='left')

In [462]:
onlinesales['GST'].isna().sum()

np.int64(0)

In [463]:
onlinesales[['Product_Category', 'GST']].head()


Product_Category   GST
0         Nest-USA  0.10
1         Nest-USA  0.10
2           Office  0.10
3          Apparel  0.18
4             Bags  0.18

In [464]:
discount.columns

Index(['Month', 'Product_Category ', 'Coupon_Code', 'Discount_pct'], dtype='object')

In [465]:
onlinesales=onlinesales.merge(discount,left_on=['Product_Category','Month_Name'],right_on=['Product_Category ','Month'],how='left')

In [466]:
onlinesales['Discount_pct'].isna().sum()

np.int64(400)

In [467]:
onlinesales['Discount_pct']=onlinesales['Discount_pct'].fillna(0)

In [468]:
onlinesales['Discount_pct'].isna().sum()

np.int64(0)

In [469]:
onlinesales.columns

Index(['CustomerID', 'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'Year', 'Month_x', 'Month_Name',
       'GST', 'Month_y', 'Product_Category ', 'Coupon_Code', 'Discount_pct'],
      dtype='object')

In [470]:
onlinesales.head

<bound method NDFrame.head of        CustomerID  Transaction_ID Transaction_Date     Product_SKU  \
0           17850           16679       2019-01-01  GGOENEBJ079499   
1           17850           16680       2019-01-01  GGOENEBJ079499   
2           17850           16681       2019-01-01  GGOEGFKQ020399   
3           17850           16682       2019-01-01  GGOEGAAB010516   
4           17850           16682       2019-01-01  GGOEGBJL013999   
...           ...             ...              ...             ...   
52919       14410           48493       2019-12-31  GGOENEBB078899   
52920       14410           48494       2019-12-31  GGOEGAEB091117   
52921       14410           48495       2019-12-31  GGOENEBQ084699   
52922       14600           48496       2019-12-31  GGOENEBQ079199   
52923       14600           48497       2019-12-31  GGOENEBQ079099   

                                     Product_Description Product_Category  \
0      Nest Learning Thermostat 3rd Gen-USA - Stainl

In [471]:
onlinesales.drop(columns=['Month_x', 'Month_y', 'Product_Category ', 'Coupon_Code'],inplace=True)

In [472]:
onlinesales.columns

Index(['CustomerID', 'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'Year', 'Month_Name', 'GST',
       'Discount_pct'],
      dtype='object')

In [473]:
onlinesales['Invoice_Value'] = ((onlinesales['Quantity'] * onlinesales['Avg_Price']) *(1 - onlinesales['Discount_pct'] / 100) *(1 + onlinesales['GST']) +onlinesales['Delivery_Charges'])

In [474]:
onlinesales['Invoice_Value'].isna().sum()

np.int64(0)

In [475]:
onlinesales[['Quantity', 'Avg_Price', 'Discount_pct', 'GST', 'Delivery_Charges', 'Invoice_Value']].head()

Quantity  Avg_Price  Discount_pct   GST  Delivery_Charges  Invoice_Value
0         1     153.71          10.0  0.10               6.5       158.6729
1         1     153.71          10.0  0.10               6.5       158.6729
2         1       2.05          10.0  0.10               6.5         8.5295
3         5      17.53          10.0  0.18               6.5        99.5843
4         1      16.50          10.0  0.18               6.5        24.0230

In [476]:
total_revenue = onlinesales['Invoice_Value'].sum().round(2)
total_orders = onlinesales['Transaction_ID'].nunique()


total_customers = onlinesales['CustomerID'].nunique()
average_order_value = (total_revenue/total_orders).round(2)

In [477]:
print('Total Revenue\n', total_revenue)


Total Revenue
 4714511.56


In [478]:
print('Total Orders \n',total_orders)

Total Orders 
 25061


In [479]:
print('Total Customers \n',total_customers)

Total Customers 
 1468


In [480]:
print('Averege Order Value \n',average_order_value)

Averege Order Value 
 188.12


In [481]:
onlinesales['Month'] = onlinesales['Transaction_Date'].dt.month

In [482]:
monthly_kpis = (
    onlinesales
    .groupby(['Year', 'Month', 'Month_Name'])
    .agg(
        Monthly_Revenue=('Invoice_Value', 'sum'),
        Monthly_Orders=('Transaction_ID', 'nunique'),
        Monthly_Customers=('CustomerID', 'nunique')
    )
    .reset_index()
)

In [483]:
monthly_kpis.head()

Year  Month Month_Name  Monthly_Revenue  Monthly_Orders  Monthly_Customers
0  2019      1        Jan     463883.05705            2102                215
1  2019      2        Feb     327896.56020            1664                109
2  2019      3        Mar     336805.20383            1991                208
3  2019      4        Apr     447999.19523            1813                224
4  2019      5        May     318556.30056            2034                200

In [484]:
category_kpis = (
    onlinesales
    .groupby('Product_Category')
    .agg(
        Category_Revenue=('Invoice_Value', 'sum'),
        Category_Quantity=('Quantity', 'sum'),
        Category_Orders=('Transaction_ID', 'nunique')
    )
    .reset_index()
    .sort_values(by='Category_Revenue', ascending=False)
)

In [485]:
category_kpis.head()

Product_Category  Category_Revenue  Category_Quantity  Category_Orders
16         Nest-USA      2.351316e+06              21430            11626
2           Apparel      7.354504e+05              32438             8129
14             Nest      4.399770e+05               2837             1974
18           Office      3.440001e+05              88383             3526
6         Drinkware      2.402678e+05              30501             2524

In [486]:
overall_kpis = pd.DataFrame({
    'Metric': [
        'Total Revenue',
        'Total Orders',
        'Total Customers',
        'Average Order Value'
    ],
    'Value': [
        total_revenue,
        total_orders,
        total_customers,
        average_order_value
    ]
})

In [487]:
overall_kpis

Metric       Value
0        Total Revenue  4714511.56
1         Total Orders    25061.00
2      Total Customers     1468.00
3  Average Order Value      188.12

In [488]:
overall_kpis

Metric       Value
0        Total Revenue  4714511.56
1         Total Orders    25061.00
2      Total Customers     1468.00
3  Average Order Value      188.12

In [489]:
monthly_kpis.head()

Year  Month Month_Name  Monthly_Revenue  Monthly_Orders  Monthly_Customers
0  2019      1        Jan     463883.05705            2102                215
1  2019      2        Feb     327896.56020            1664                109
2  2019      3        Mar     336805.20383            1991                208
3  2019      4        Apr     447999.19523            1813                224
4  2019      5        May     318556.30056            2034                200

In [490]:
category_kpis.head()

Product_Category  Category_Revenue  Category_Quantity  Category_Orders
16         Nest-USA      2.351316e+06              21430            11626
2           Apparel      7.354504e+05              32438             8129
14             Nest      4.399770e+05               2837             1974
18           Office      3.440001e+05              88383             3526
6         Drinkware      2.402678e+05              30501             2524

In [491]:
overall_kpis.to_csv(
    r"C:\python_projects\machine_learning\Capstone_Finding_Marketing_Insights\Power_BI\overall_kpis.csv",
    index=False)
monthly_kpis.to_csv(
    r"C:\python_projects\machine_learning\Capstone_Finding_Marketing_Insights\Power_BI\monthly_kpis.csv",
    index=False)
category_kpis.to_csv(
    r"C:\python_projects\machine_learning\Capstone_Finding_Marketing_Insights\Power_BI\category_kpis.csv",
    index=False)

In [492]:
customer_features = (
    onlinesales
    .groupby('CustomerID')
    .agg(
        Total_Revenue=('Invoice_Value', 'sum'),
        Total_Orders=('Transaction_ID', 'nunique'),
        Total_Quantity=('Quantity', 'sum'),
        Avg_Order_Value=('Invoice_Value', 'mean'),
        First_Purchase_Date=('Transaction_Date', 'min'),
        Last_Purchase_Date=('Transaction_Date', 'max')
    )
    .reset_index()
)

In [493]:
customer_features.head()

CustomerID  Total_Revenue  Total_Orders  Total_Quantity  Avg_Order_Value  \
0       12346      174.98174             1               3        87.490870   
1       12347    12090.29580            31             342       201.504930   
2       12348     1501.92620             8             209        65.301139   
3       12350     1183.71394            11              21        69.630232   
4       12356     1753.45086            13              56        48.706968   

  First_Purchase_Date Last_Purchase_Date  
0          2019-09-15         2019-09-15  
1          2019-03-24         2019-11-02  
2          2019-06-22         2019-10-19  
3          2019-12-14         2019-12-14  
4          2019-09-15         2019-09-15

In [495]:
reference_date = onlinesales['Transaction_Date'].max()
customer_features['Recency_Days'] = (reference_date - customer_features['Last_Purchase_Date']).dt.days
customer_features['Active_Days'] = (customer_features['Last_Purchase_Date'] - customer_features['First_Purchase_Date']).dt.days

In [496]:
customer_features[['CustomerID','Recency_Days','Active_Days']].head()

CustomerID  Recency_Days  Active_Days
0       12346           107            0
1       12347            59          223
2       12348            73          119
3       12350            17            0
4       12356           107            0

In [497]:
customer_ml = customer_features.merge(customers,on='CustomerID',how='left')

In [498]:
customer_ml.head()

CustomerID  Total_Revenue  Total_Orders  Total_Quantity  Avg_Order_Value  \
0       12346      174.98174             1               3        87.490870   
1       12347    12090.29580            31             342       201.504930   
2       12348     1501.92620             8             209        65.301139   
3       12350     1183.71394            11              21        69.630232   
4       12356     1753.45086            13              56        48.706968   

  First_Purchase_Date Last_Purchase_Date  Recency_Days  Active_Days Gender  \
0          2019-09-15         2019-09-15           107            0      F   
1          2019-03-24         2019-11-02            59          223      M   
2          2019-06-22         2019-10-19            73          119      M   
3          2019-12-14         2019-12-14            17            0      M   
4          2019-09-15         2019-09-15           107            0      F   

     Location  Tenure_Months  
0    New York             31  
1    New York             20  
2  California             39  
3  California             25  
4     Chicago             31

In [499]:
customer_ml['Customer_Value_Segment'] = pd.qcut(customer_ml['Total_Revenue'],q=3,labels=['Low','Medium','High'])

In [500]:
customer_ml['Customer_Value_Segment'].value_counts()

Customer_Value_Segment
High      490
Low       489
Medium    489
Name: count, dtype: int64

In [501]:
y = customer_ml['Customer_Value_Segment']

In [502]:
X = customer_ml.drop(columns=['CustomerID','First_Purchase_Date','Last_Purchase_Date','Customer_Value_Segment'])

In [503]:
X.head()

Total_Revenue  Total_Orders  Total_Quantity  Avg_Order_Value  Recency_Days  \
0      174.98174             1               3        87.490870           107   
1    12090.29580            31             342       201.504930            59   
2     1501.92620             8             209        65.301139            73   
3     1183.71394            11              21        69.630232            17   
4     1753.45086            13              56        48.706968           107   

   Active_Days Gender    Location  Tenure_Months  
0            0      F    New York             31  
1          223      M    New York             20  
2          119      M  California             39  
3            0      M  California             25  
4            0      F     Chicago             31

In [504]:
X = pd.get_dummies(X, drop_first=True)

In [506]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42,stratify=y)

In [507]:
X_train.shape

(1101, 12)

In [508]:
X_test.shape

(367, 12)

In [509]:
y_train.value_counts()

Customer_Value_Segment
Low       367
Medium    367
High      367
Name: count, dtype: int64

In [510]:
y_test.value_counts()

Customer_Value_Segment
High      123
Low       122
Medium    122
Name: count, dtype: int64

In [512]:
log_reg = LogisticRegression(max_iter=1000,multi_class='multinomial')

In [513]:
log_reg.fit(X_train, y_train)

C:\Users\singh\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\singh\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000, multi_class='multinomial')

In [514]:
y_pred = log_reg.predict(X_test)

In [516]:
print(confusion_matrix(y_test, y_pred))

[[110   0  13]
 [  0 115   7]
 [ 15   6 101]]


In [517]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        High       0.88      0.89      0.89       123
         Low       0.95      0.94      0.95       122
      Medium       0.83      0.83      0.83       122

    accuracy                           0.89       367
   macro avg       0.89      0.89      0.89       367
weighted avg       0.89      0.89      0.89       367



In [519]:
dt_model = DecisionTreeClassifier(max_depth=5,min_samples_split=20,random_state=42)

In [520]:
dt_model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, min_samples_split=20, random_state=42)

In [521]:
y_pred_dt = dt_model.predict(X_test)

In [523]:
print(confusion_matrix(y_test, y_pred_dt))

[[123   0   0]
 [  0 122   0]
 [  0   0 122]]


In [524]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

        High       1.00      1.00      1.00       123
         Low       1.00      1.00      1.00       122
      Medium       1.00      1.00      1.00       122

    accuracy                           1.00       367
   macro avg       1.00      1.00      1.00       367
weighted avg       1.00      1.00      1.00       367



In [525]:
feature_importance_dt = pd.DataFrame({'Feature': X.columns,'Importance': dt_model.feature_importances_}).sort_values(by='Importance', ascending=False)

In [526]:
feature_importance_dt.head(10)

Feature  Importance
0        Total_Revenue         1.0
1         Total_Orders         0.0
2       Total_Quantity         0.0
3      Avg_Order_Value         0.0
4         Recency_Days         0.0
5          Active_Days         0.0
6        Tenure_Months         0.0
7             Gender_M         0.0
8     Location_Chicago         0.0
9  Location_New Jersey         0.0

In [527]:
X = X.drop(columns=['Total_Revenue'])

In [528]:
X.shape

(1468, 11)

In [529]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42,stratify=y)

In [530]:
dt_model = DecisionTreeClassifier(max_depth=5,min_samples_split=20,random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

In [531]:
print(confusion_matrix(y_test, y_pred_dt))

[[114   1   8]
 [  0 105  17]
 [  7  19  96]]


In [532]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

        High       0.94      0.93      0.93       123
         Low       0.84      0.86      0.85       122
      Medium       0.79      0.79      0.79       122

    accuracy                           0.86       367
   macro avg       0.86      0.86      0.86       367
weighted avg       0.86      0.86      0.86       367



In [533]:
pd.DataFrame({'Feature': X.columns,'Importance': dt_model.feature_importances_}).sort_values(by='Importance', ascending=False).head(10)

Feature  Importance
0         Total_Orders    0.808282
2      Avg_Order_Value    0.107491
1       Total_Quantity    0.079435
5        Tenure_Months    0.003661
4          Active_Days    0.001131
3         Recency_Days    0.000000
6             Gender_M    0.000000
7     Location_Chicago    0.000000
8  Location_New Jersey    0.000000
9    Location_New York    0.000000

In [535]:
rf_model = RandomForestClassifier(n_estimators=200,max_depth=6,min_samples_split=20,random_state=42)

In [536]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=6, min_samples_split=20, n_estimators=200,
                       random_state=42)

In [537]:
y_pred_rf = rf_model.predict(X_test)

In [538]:
print(confusion_matrix(y_test, y_pred_rf))

[[112   1  10]
 [  0 108  14]
 [  3  15 104]]


In [539]:
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

        High       0.97      0.91      0.94       123
         Low       0.87      0.89      0.88       122
      Medium       0.81      0.85      0.83       122

    accuracy                           0.88       367
   macro avg       0.89      0.88      0.88       367
weighted avg       0.89      0.88      0.88       367



In [540]:
rf_importance = pd.DataFrame({'Feature': X.columns,'Importance': rf_model.feature_importances_}).sort_values(by='Importance', ascending=False)

In [541]:
rf_importance.head(10)

Feature  Importance
0             Total_Orders    0.448725
1           Total_Quantity    0.264229
2          Avg_Order_Value    0.157372
4              Active_Days    0.068284
3             Recency_Days    0.034010
5            Tenure_Months    0.016747
6                 Gender_M    0.002577
7         Location_Chicago    0.002335
10  Location_Washington DC    0.002057
8      Location_New Jersey    0.001870

In [542]:
rf_importance.to_csv(r"C:\python_projects\machine_learning\Capstone_Finding_Marketing_Insights\Power_BI\rf_feature_importance.csv",index=False)

In [543]:
ml_predictions = X_test.copy()
ml_predictions['Actual_Segment'] = y_test.values
ml_predictions['Predicted_Segment'] = y_pred_rf

In [544]:
ml_predictions.to_csv(r"C:\python_projects\machine_learning\Capstone_Finding_Marketing_Insights\Power_BI\customer_value_predictions.csv",index=False)

The project analyzed e-commerce sales and customer data to generate business KPIs and predict customer value segments. A Random Forest model was used for customer segmentation, showing that purchase frequency is the key driver of customer value. The results are visualized in Power BI for business decision-making.